cors:
  originPatterns: http://localhost:8080,http://localhost:3000
spring:
  application:
    name: segundo-exemplo
  datasource:
    url: jdbc:postgresql://localhost:5432/segundo_exemplo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
    show-sql: true
    open-in-view: false
loggin:
  level:
    root: INFO
    #curso.spring.boot: DEBUG
spring-doc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true
