spring:
  application:
    name: segundo-exemplo
  datasource:
    url: jdbc:postgresql://localhost:5432/segundo_exemplo
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: true
    open-in-view: false
loggin:
  level:
    curso.spring.boot: DEBUG
