INSERT INTO person (first_name, last_name, address, gender, enabled) VALUES
('Manuela', 'Moreira', 'Núcleo Mariane Silveira, 23', 'Feminino', true),
('Maitê', 'Correia', 'Ladeira Otávio Jesus, 6', 'Feminino', true),
('Igor', 'Costa', 'Sítio Cauã da Conceição, 80', 'Masculino', true),
('Emilly', 'da Paz', 'Lago Joaquim da Cruz, 96', 'Feminino', true),
('Calebe', 'Fogaça', 'Viela de Moraes, 88', 'Masculino', true),
('Caio', 'Rocha', 'Colônia Ferreira, 31', 'Masculino', true),
('Yago', 'Melo', 'Residencial de Martins, 779', 'Masculino', true),
('Pietro', 'Campos', 'Praia de Cavalcanti', 'Masculino', true),
('Anthony', 'Almeida', 'Área Juliana Nascimento, 84', 'Masculino', true),
('Enzo', 'Monteiro', 'Vale de Porto, 4', 'Masculino', true),
('Bianca', 'Silveira', 'Praia Luiz Gustavo Cunha, 9', 'Feminino', true),
('Rafaela', 'Silveira', 'Chácara de Gomes, 90', 'Feminino', true),
('Clara', 'da Mata', 'Lago Joana Alves, 20', 'Feminino', true),
('Pietra', 'da Rocha', 'Vereda Mirella Costela, 4', 'Feminino', true),
('Eloah', 'Nascimento', 'Vale Fogaça, 29', 'Feminino', true),
('Ana Laura', 'Pinto', 'Viela Araújo, 27', 'Feminino', true),
('João Vitor', 'Moreira', 'Pátio de Cardoso, 798', 'Masculino', true),
('Laís', 'Costela', 'Área de Rezende, 882', 'Feminino', true),
('Marina', 'Costa', 'Rodovia de Cardoso', 'Feminino', true),
('Laís', 'da Rosa', 'Residencial Miguel Pereira, 31', 'Feminino', true),
('Luiz Henrique', 'Gomes', 'Favela de da Rosa, 74', 'Masculino', true),
('Kevin', 'Fogaça', 'Fazenda Esther Duarte', 'Masculino', true),
('Luigi', 'da Costa', 'Loteamento Eduardo Vieira, 48', 'Masculino', true),
('Guilherme', 'Pinto', 'Lagoa de Pereira, 41', 'Masculino', true),
('Miguel', 'Peixoto', 'Vereda Gomes, 48', 'Masculino', true),
('Maria Vitória', 'Ribeiro', 'Colônia Peixoto, 9', 'Feminino', true),
('Rodrigo', 'Melo', 'Feira de Novaes, 14', 'Masculino', true),
('André', 'Costela', 'Núcleo Costa, 61', 'Masculino', true),
('Lorenzo', 'Cavalcanti', 'Pátio Pedro Cardoso, 30', 'Masculino', true),
('Diego', 'Mendes', 'Feira Nicolas Souza, 79', 'Masculino', true),
('Cauã', 'da Rocha', 'Praça da Rosa, 57', 'Masculino', true),
('Maria Eduarda', 'Costa', 'Alameda Caldeira, 7', 'Feminino', true),
('Diogo', 'Jesus', 'Vale de Costela, 5', 'Masculino', true),
('Maria Luiza', 'da Cunha', 'Sítio Benício Cunha, 273', 'Feminino', true),
('Camila', 'Pereira', 'Vereda Monteiro, 99', 'Feminino', true),
('Fernando', 'Vieira', 'Morro de Cardoso, 3', 'Masculino', true),
('Alexia', 'Fogaça', 'Conjunto Lucas Gabriel da Cunha, 72', 'Feminino', true),
('Vitor Gabriel', 'da Rocha', 'Praia Ferreira, 95', 'Masculino', true),
('Stephany', 'Carvalho', 'Núcleo da Conceição, 25', 'Feminino', true),
('Letícia', 'Teixeira', 'Quadra Souza, 61', 'Feminino', true),
('Eduarda', 'da Cunha', 'Largo Correia, 79', 'Feminino', true),
('Pedro Miguel', 'da Rosa', 'Viela Silva, 34', 'Masculino', true),
('Sophie', 'Aragão', 'Jardim Rafaela Almeida, 72', 'Feminino', true),
('Sarah', 'Pires', 'Ladeira Emanuella Barbosa, 24', 'Feminino', true),
('Benício', 'da Cunha', 'Distrito Noah da Cruz, 9', 'Masculino', true),
('Francisco', 'da Conceição', 'Rua Guilherme da Mata, 96', 'Masculino', true),
('Ana Beatriz', 'Jesus', 'Área de Gonçalves, 94', 'Feminino', true),
('Cecília', 'Monteiro', 'Residencial Caroline Farias', 'Feminino', true),
('Luiz Fernando', 'da Mata', 'Sítio Alves, 7', 'Masculino', true),
('Stephany', 'Martins', 'Conjunto de da Cruz, 53', 'Feminino', true),
('Pietra', 'Gomes', 'Lago Pires, 99', 'Feminino', true),
('Leandro', 'Dias', 'Feira Melo, 976', 'Masculino', true),
('Thiago', 'Cunha', 'Condomínio de Moreira', 'Masculino', true),
('Maria Luiza', 'Peixoto', 'Alameda Igor da Paz, 325', 'Feminino', true),
('Matheus', 'Cardoso', 'Estrada Duarte, 953', 'Masculino', true),
('Bruna', 'Moreira', 'Estação de Santos, 1', 'Feminino', true),
('Yago', 'Pires', 'Largo Leonardo Nascimento', 'Masculino', true),
('Ana Carolina', 'Cunha', 'Setor de Pereira, 70', 'Feminino', true),
('Davi Lucca', 'Rocha', 'Travessa Erick Castro, 20', 'Masculino', true),
('Giovanna', 'da Mota', 'Praça de Freitas, 76', 'Feminino', true),
('João Guilherme', 'Alves', 'Aeroporto Brenda Barbosa, 4', 'Masculino', true),
('Lívia', 'Jesus', 'Condomínio Rocha, 93', 'Feminino', true),
('Eduardo', 'Caldeira', 'Lagoa de Barros, 935', 'Masculino', true),
('Bruno', 'Pinto', 'Lagoa Renan Moura, 77', 'Masculino', true),
('Ana Julia', 'Aragão', 'Parque de Fernandes, 282', 'Feminino', true),
('Felipe', 'da Costa', 'Jardim de Correia, 7', 'Masculino', true),
('Maria Clara', 'Costa', 'Residencial de Nascimento, 76', 'Feminino', true),
('Brenda', 'da Rosa', 'Praia de da Mota, 9', 'Feminino', true),
('Pedro Henrique', 'Novaes', 'Setor Pinto, 68', 'Masculino', true),
('Marina', 'Porto', 'Lagoa de da Mota, 562', 'Feminino', true),
('Eduardo', 'Ribeiro', 'Quadra Cardoso', 'Masculino', true),
('Marcelo', 'Rocha', 'Alameda Nascimento, 62', 'Masculino', true),
('Juan', 'da Luz', 'Estrada João Lucas Azevedo, 946', 'Masculino', true),
('Igor', 'Dias', 'Praça de Santos, 28', 'Masculino', true),
('Olivia', 'Gomes', 'Núcleo Lopes, 689', 'Feminino', true),
('Daniela', 'Rocha', 'Sítio de da Cruz, 813', 'Feminino', true),
('Lavínia', 'Pires', 'Esplanada de Monteiro, 6', 'Feminino', true),
('Guilherme', 'da Cunha', 'Estrada Maria Vitória Moreira', 'Masculino', true),
('Antônio', 'Cardoso', 'Favela Nogueira, 42', 'Masculino', true),
('Cauê', 'Rocha', 'Conjunto de Souza, 76', 'Masculino', true),
('Cauã', 'Fernandes', 'Ladeira de Sales', 'Masculino', true),
('Mariane', 'Nogueira', 'Praia de Fernandes, 80', 'Feminino', true),
('Isabella', 'Gonçalves', 'Campo Fernandes, 1', 'Feminino', true),
('Antônio', 'Porto', 'Praça de Souza, 31', 'Masculino', true),
('Pietro', 'Teixeira', 'Lago Nathan Caldeira', 'Masculino', true),
('Lorena', 'Freitas', 'Estrada da Cunha', 'Feminino', true),
('Enzo Gabriel', 'Moreira', 'Sítio de Ferreira, 180', 'Masculino', true),
('Luiz Gustavo', 'da Rosa', 'Aeroporto da Costa, 313', 'Masculino', true),
('Enzo', 'Silveira', 'Lago Daniela Sales', 'Masculino', true),
('Maria Sophia', 'Azevedo', 'Chácara Davi Lucas Souza, 15', 'Feminino', true),
('Sophie', 'da Rocha', 'Núcleo Marcos Vinicius Rezende, 78', 'Feminino', true),
('Isis', 'da Mota', 'Fazenda Nogueira, 5', 'Feminino', true),
('Davi Lucca', 'Rocha', 'Aeroporto Isadora Pinto, 85', 'Masculino', true),
('Vitor Hugo', 'Cavalcanti', 'Trecho de Pereira', 'Masculino', true),
('Heitor', 'Silva', 'Parque João Guilherme Melo, 17', 'Masculino', true),
('Antônio', 'Lopes', 'Favela de Costa, 80', 'Masculino', true),
('Lucas Gabriel', 'Freitas', 'Morro Fernando Jesus, 44', 'Masculino', true),
('Alexandre', 'Sales', 'Feira Ferreira, 280', 'Masculino', true),
('Thiago', 'Teixeira', 'Fazenda Agatha Aragão, 66', 'Masculino', true),
('Maria Eduarda', 'Moraes', 'Rua João Lucas Silveira, 4', 'Feminino', true);